version: '3'
services:
  backend-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-node
    container_name: backend-node
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend-node-network
networks:
  backend-node-network: